import { expect, test } from '@playwright/test';
import { tools, disclose } from './workspace-test-helpers';

test('workspace tools resize, collapse and preserve a measured replay across view changes', async ({
	page
}, testInfo) => {
	const errors: string[] = [];
	page.on('pageerror', (error) => errors.push(error.message));
	await page.setViewportSize({ width: 1440, height: 1000 });
	await page.goto('/?view=tinystories');
	const lab = page.locator('.token-story-lab');
	await lab.locator('.archive-item.reference').filter({ hasText: 'Live replay' }).click();
	const live = lab.getByRole('region', { name: 'Live token generation', exact: true });
	await expect(live.locator('.trace-tokens button')).toHaveCount(24);
	await expect(lab.locator('.evidence-drawer')).not.toHaveAttribute('open');
	await tools(lab, 'inspector');
	await lab.getByLabel('Subword unit ID', { exact: true }).fill('1403');
	await live.getByRole('button', { name: 'Inspect recorded token 11', exact: true }).click();
	await live.getByRole('button', { name: 'Inspect recorded layer 3', exact: true }).click();
	await expect(live.getByLabel('Selected channel activation')).toHaveText('1.8640');
	const resize = lab.getByRole('slider', { name: 'Resize tools panel' });
	await resize.press('ArrowLeft');
	await expect(resize).toHaveAttribute('aria-valuenow', '384');
	const box = await resize.boundingBox();
	expect(box).not.toBeNull();
	await page.mouse.move(box!.x + box!.width / 2, box!.y + 90);
	await page.mouse.down();
	await page.mouse.move(box!.x - 74, box!.y + 90);
	await page.mouse.up();
	const width = Number(await resize.getAttribute('aria-valuenow'));
	expect(width).toBeGreaterThan(450);
	expect(width).toBeLessThan(480);
	const canvas = lab.locator('.token-story-field canvas');
	const before = (await canvas.boundingBox())!.width;
	await lab.getByRole('button', { name: 'Collapse tools', exact: true }).click();
	await expect(lab.getByLabel('Subword unit ID')).toBeHidden();
	await expect.poll(async () => (await canvas.boundingBox())!.width).toBeGreaterThan(before + 350);
	await tools(lab, 'inspector');
	await expect(lab.getByLabel('Subword unit ID')).toHaveValue('1403');
	await expect(live).toHaveAttribute('data-frame', '10');
	await expect(resize).toHaveAttribute('aria-valuenow', String(width));
	await page.reload();
	await expect(resize).toHaveAttribute('aria-valuenow', String(width));
	await lab.locator('.archive-item.reference').filter({ hasText: 'Live replay' }).click();
	await tools(lab, 'inspector');
	await lab.getByLabel('Subword unit ID').fill('1403');
	await live.getByRole('button', { name: 'Inspect recorded token 11', exact: true }).click();
	await live.getByRole('button', { name: 'Inspect recorded layer 3', exact: true }).click();
	await page.getByRole('link', { name: 'Tissue home' }).focus();
	await page.evaluate(() => window.scrollTo(0, 0));
	await page.screenshot({ path: testInfo.outputPath('workspace-desktop.png') });
	await page.getByRole('button', { name: 'Switch to light mode' }).click();
	await page.screenshot({ path: testInfo.outputPath('workspace-light.png') });
	await page.setViewportSize({ width: 390, height: 844 });
	await expect(resize).toBeHidden();
	await lab.getByRole('button', { name: 'Collapse tools', exact: true }).click();
	await expect(lab.getByRole('button', { name: 'Expand tools', exact: true })).toBeVisible();
	expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
	await disclose(lab, 'Measurement details');
	await disclose(lab, 'Samples & evidence');
	expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
	await page.screenshot({ path: testInfo.outputPath('workspace-mobile.png'), fullPage: true });
	expect(errors).toEqual([]);
});
